Rails/Blog/config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'blog#index'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  get  '/signin',   to: 'user#signin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/Blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails/Blog/app/models/user.rb
class User < ApplicationRecord
  attr_accessor :email
  before_save { self.email = email.downcase }
  validates :email,
            presence:       { message: ': Please enter email' },
            uniqueness:     { message: ': This email has already been registered' },
            format:         { with: /\A.+@.+\z/,
                              message: ': Invalid email address' }
  validates :pass,
            presence:       { message: ': Please enter password' },
            length:         { minimum: 8,
                              message: ': Must be at least 8 characters' },
            confirmation:   { message: ': Password not match' }
end

Rails/Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Rails/Blog/app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @users = User.all
  end
end

Rails/Blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render 'new'
    end

  end
  def signin

  end
  def user_params
    params.require(:user).permit(:email, :pass)
  end
end

Rails/Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/Blog/app/helpers/blog_helper.rb
module BlogHelper
end

Rails/Blog/app/helpers/users_helper.rb
module UsersHelper
end

Rails/Blog/app/views/blog/index.html.erb
<%= link_to 'signup', new_user_path %><br>
<%= link_to 'signin', users_path %>

Rails/Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

Rails/Blog/app/views/users/new.html.erb
<%= form_with scope: :user, url: users_path, local: true do |form| %>
 <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :pass %><br>
    <%= form.password_field :pass %>
  </p>

  <p>
    <%= form.label :pass_confirmation %><br>
    <%= form.password_field :pass_confirmation %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', root_path %>

Rails/Blog/app/views/users/show.html.erb
<%= @user.email %><br>
<%= @user.pass %>